### ISSUE TITLE
Failed installing llvm-openmp@romp-mod 

### ISSUE THREAD

**Issue by peihunglin** [zygyz/romp#12]
The following error was seen during installing llvm-openmp@romp-mod when building a Docker image based on the spack/ubuntu-bionic image.

Step 5/10 : RUN spack install llvm-openmp@romp-mod
 ---> Running in e367ca158173
[+] /opt/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/pkgconf-1.7.4-qlu7hjpnqskh4rj73nwj7sqtwqz3uagl
[+] /opt/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/berkeley-db-18.1.40-oxrqyphgavukfdfwiusuogfoyxiil6ef
[+] /opt/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/zlib-1.2.11-fegtmskef3daxdtyp3x3m6zz2fjfpxpq
[+] /opt/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/ncurses-6.2-3vn4oo27wqdal42ouzs6qconqg66utfv
[+] /opt/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/readline-8.1-6wgznlz5e2rdgtijk3zaklavjv7xiime
[+] /opt/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/gdbm-1.19-nb5ufq5zz6xhnxchftekanrmracdqoi6
[+] /opt/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/perl-5.34.0-mhmghot65u6ztktgxsq5saucslje6sez
[+] /opt/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/openssl-1.1.1k-hsmx6mxdn6ls4yus2lcurnuvlb6vqvyt
[+] /opt/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/cmake-3.20.3-lpjhnv4pz77i3mysbgxysdnlevd237wg
==> Installing llvm-openmp-romp-mod-ov6cskwquboafnjaslyghcqjfymtersi
==> No binary for llvm-openmp-romp-mod-ov6cskwquboafnjaslyghcqjfymtersi found: installing from source
==> Warning: Missing a source id for llvm-openmp@romp-mod
==> Warning: Missing a source id for llvm-openmp@romp-mod
==> Warning: There is no checksum on file to fetch llvm-openmp@romp-mod safely.
==> Error: FetchError: Will not fetch llvm-openmp@romp-mod
    Add a checksum or use --no-checksum to skip this check.

/opt/spack/lib/spack/spack/package.py:1341, in do_fetch:
       1338                              .format(ck_msg))
       1339
       1340            if not ignore_checksum:
  \>\>   1341                raise FetchError("Will not fetch %s" %
       1342                                 self.spec.format('{name}{@version}'), ck_msg)
       1343
       1344        deprecated = spack.config.get('config:deprecated')

**Comment by chfogelman** [comment]
I had a similar issue myself. Did you use the author's forked branch of spack?

**Comment by peihunglin** [comment]
> I had a similar issue myself. Did you use the author's forked branch of spack?

I used the docker image provided from Spack.

**Comment by zygyz** [comment]
Hi Pei-Hung,

Thanks for the email. I was heavily involved in my company's projects. Let
me take a look and get back to you soon.

Best,
Yizi

**Comment by zygyz** [comment]
I will update the library to using production llvm-project/openmp with some code mod to support optional ompt events.
