### ISSUE TITLE
can not run spack install llvm-openmp@romp-mod%gcc@9.2.0

### ISSUE THREAD

**Issue by World-Worst-Detector** [zygyz/romp#3]
cuda do not support gcc9. How did you install the llvm-openmp with gcc 9.2.0?

**Comment by zygyz** [comment]
> cuda do not support gcc9. How did you install the llvm-openmp with gcc 9.2.0?

Please make sure you configure spack to include the compiler option for using gcc9.2.0.
The instruction is listed in the readme. I don't see reason why llvm library cannot be compiled
with gcc. The llvm-openmp may support gpu offloading, but as far as I know I don't see 
why cuda would be involved. 

`spack config edit compilers`

You need to checkout my branch of spack, instead of the master branch in their repository. 
Because it contains some changes to the llvm-openmp package.py file that pick my branch
of llvm-openmp. Why using my branch of llvm-openmp? Because OpenMP 5.0 defines the 
OMPT callbacks that are required by race detector, but some of them are not implemented.
I added the missing pieces to make the whole thing work. 
  ```
   git clone git@github.com:zygyz/spack.git
   git checkout romp-build
```

Also, cuda support is out of the scope of ROMP.

**Comment by World-Worst-Detector** [comment]
Thank you.  But I got those errors:
/usr/local/cuda/include/crt/host_config.h:119:2: error: #error -- u
            nsupported GNU version! gcc versions later than 7 are not supported
            !
CMake Error at omptarget-nvptx_generated_omptarget-nvptx.cu.o.RelWi
            thDebInfo.cmake:215 (message):
 make[2]: *** [libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nv
            ptx.dir/src/omptarget-nvptx_generated_omptarget-nvptx.cu.o] Error 1

**Comment by zygyz** [comment]
> Thank you. But I got those errors:
> /usr/local/cuda/include/crt/host_config.h:119:2: error: #error -- u
> nsupported GNU version! gcc versions later than 7 are not supported
> !
> CMake Error at omptarget-nvptx_generated_omptarget-nvptx.cu.o.RelWi
> thDebInfo.cmake:215 (message):
> make[2]: *** [libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nv
> ptx.dir/src/omptarget-nvptx_generated_omptarget-nvptx.cu.o] Error 1

Thanks! This is an interesting problem.  
May I get the commands you run that trigger this error message?

**Comment by nbushehri** [comment]
I'm getting a different error when trying to install llvm-opnemp using spack. I've followed the readme and reach the step to install llvm-openmp using spack by running run the following command:

`spack install llvm-openmp@romp-mod%gcc@9.2.0`

The build starts but it ends with errors: 
```
...
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'
51 errors found in build log:
[ 41%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_error.cpp.o
...
>> 225    /home/n/.spack/stage/llvm-openmp-romp-mod-kydftrwqfftjaj5tq23zigtrzlsyqmy6/spack-src/runtime/src/kmp_csupport.cpp:283:5: error: 'omp_frame_t' was not declared in this scope; did you mean 'ompt_frame_t'?
...
491    make[1]: Leaving directory '/home/n/.spack/stage/llvm-openmp-romp-mod-kydftrwqfftjaj5tq23zigtrzlsyqmy6/spack-build'
492    Makefile:132: recipe for target 'all' failed
>> 493    make: *** [all] Error 2

```

**Comment by zygyz** [comment]
> I'm getting a different error when trying to install llvm-opnemp using spack. I've followed the readme and reach the step to install llvm-openmp using spack by running run the following command:
> 
> `spack install llvm-openmp@romp-mod%gcc@9.2.0`
> 
> The build starts but it ends with errors:
> 
> ```
> ...
> ==> Error: ProcessError: Command exited with status 2:
>     'make' '-j16'
> 51 errors found in build log:
> [ 41%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_error.cpp.o
> ...
> >> 225    /home/n/.spack/stage/llvm-openmp-romp-mod-kydftrwqfftjaj5tq23zigtrzlsyqmy6/spack-src/runtime/src/kmp_csupport.cpp:283:5: error: 'omp_frame_t' was not declared in this scope; did you mean 'ompt_frame_t'?
> ...
> 491    make[1]: Leaving directory '/home/n/.spack/stage/llvm-openmp-romp-mod-kydftrwqfftjaj5tq23zigtrzlsyqmy6/spack-build'
> 492    Makefile:132: recipe for target 'all' failed
> >> 493    make: *** [all] Error 2
> ```

Thanks for the feedback. 
The failure is caused by my changes to the spack configuration file for llvm-openmp. 
Please pull the `romp-mod` branch of  `git@github.com:zygyz/spack.git` again to 
get the latest update. And then try again. Thanks!

**Comment by World-Worst-Detector** [comment]
> > I'm getting a different error when trying to install llvm-opnemp using spack. I've followed the readme and reach the step to install llvm-openmp using spack by running run the following command:
> > `spack install llvm-openmp@romp-mod%gcc@9.2.0`
> > The build starts but it ends with errors:
> > ```
> > ...
> > ==> Error: ProcessError: Command exited with status 2:
> >     'make' '-j16'
> > 51 errors found in build log:
> > [ 41%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_error.cpp.o
> > ...
> > >> 225    /home/n/.spack/stage/llvm-openmp-romp-mod-kydftrwqfftjaj5tq23zigtrzlsyqmy6/spack-src/runtime/src/kmp_csupport.cpp:283:5: error: 'omp_frame_t' was not declared in this scope; did you mean 'ompt_frame_t'?
> > ...
> > 491    make[1]: Leaving directory '/home/n/.spack/stage/llvm-openmp-romp-mod-kydftrwqfftjaj5tq23zigtrzlsyqmy6/spack-build'
> > 492    Makefile:132: recipe for target 'all' failed
> > >> 493    make: *** [all] Error 2
> > ```
> 
> Thanks for the feedback.
> The failure is caused by my changes to the spack configuration file for llvm-openmp.
> Please pull the `romp-mod` branch of `git@github.com:zygyz/spack.git` again to
> get the latest update. And then try again. Thanks!

I didn't find a branch called romp-mod, did you mean the romp build?

**Comment by World-Worst-Detector** [comment]
> > Thank you. But I got those errors:
> > /usr/local/cuda/include/crt/host_config.h:119:2: error: #error -- u
> > nsupported GNU version! gcc versions later than 7 are not supported
> > !
> > CMake Error at omptarget-nvptx_generated_omptarget-nvptx.cu.o.RelWi
> > thDebInfo.cmake:215 (message):
> > make[2]: *** [libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nv
> > ptx.dir/src/omptarget-nvptx_generated_omptarget-nvptx.cu.o] Error 1
> 
> Thanks! This is an interesting problem.
> May I get the commands you run that trigger this error message?

I just use the command:

spack install llvm-openmp@romp-mod%gcc@9.2.0

**Comment by zygyz** [comment]
> > > I'm getting a different error when trying to install llvm-opnemp using spack. I've followed the readme and reach the step to install llvm-openmp using spack by running run the following command:
> > > `spack install llvm-openmp@romp-mod%gcc@9.2.0`
> > > The build starts but it ends with errors:
> > > ```
> > > ...
> > > ==> Error: ProcessError: Command exited with status 2:
> > >     'make' '-j16'
> > > 51 errors found in build log:
> > > [ 41%] Building CXX object runtime/src/CMakeFiles/omp.dir/kmp_error.cpp.o
> > > ...
> > > >> 225    /home/n/.spack/stage/llvm-openmp-romp-mod-kydftrwqfftjaj5tq23zigtrzlsyqmy6/spack-src/runtime/src/kmp_csupport.cpp:283:5: error: 'omp_frame_t' was not declared in this scope; did you mean 'ompt_frame_t'?
> > > ...
> > > 491    make[1]: Leaving directory '/home/n/.spack/stage/llvm-openmp-romp-mod-kydftrwqfftjaj5tq23zigtrzlsyqmy6/spack-build'
> > > 492    Makefile:132: recipe for target 'all' failed
> > > >> 493    make: *** [all] Error 2
> > > ```
> > 
> > 
> > Thanks for the feedback.
> > The failure is caused by my changes to the spack configuration file for llvm-openmp.
> > Please pull the `romp-mod` branch of `git@github.com:zygyz/spack.git` again to
> > get the latest update. And then try again. Thanks!
> 
> I didn't find a branch called romp-mod, did you mean the romp build?

Yes, you are right.

**Comment by zygyz** [comment]
> > > Thank you. But I got those errors:
> > > /usr/local/cuda/include/crt/host_config.h:119:2: error: #error -- u
> > > nsupported GNU version! gcc versions later than 7 are not supported
> > > !
> > > CMake Error at omptarget-nvptx_generated_omptarget-nvptx.cu.o.RelWi
> > > thDebInfo.cmake:215 (message):
> > > make[2]: *** [libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nv
> > > ptx.dir/src/omptarget-nvptx_generated_omptarget-nvptx.cu.o] Error 1
> > 
> > 
> > Thanks! This is an interesting problem.
> > May I get the commands you run that trigger this error message?
> 
> I just use the command:
> 
> spack install llvm-openmp@romp-mod%gcc@9.2.0

I see the `/usr/local/cuda/include/crt/host_config.h`  header file. I think if gcc is also installed using spack, header files in system directory would not be used. The idea of `spack` is to make building packages machine/system independent, i.e., all dependent packages would be installed in a spack specific location, instead of using existing libraries in the system.

**Comment by World-Worst-Detector** [comment]
> > > > Thank you. But I got those errors:
> > > > /usr/local/cuda/include/crt/host_config.h:119:2: error: #error -- u
> > > > nsupported GNU version! gcc versions later than 7 are not supported
> > > > !
> > > > CMake Error at omptarget-nvptx_generated_omptarget-nvptx.cu.o.RelWi
> > > > thDebInfo.cmake:215 (message):
> > > > make[2]: *** [libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nv
> > > > ptx.dir/src/omptarget-nvptx_generated_omptarget-nvptx.cu.o] Error 1
> > > 
> > > 
> > > Thanks! This is an interesting problem.
> > > May I get the commands you run that trigger this error message?
> > 
> > 
> > I just use the command:
> > spack install llvm-openmp@romp-mod%gcc@9.2.0
> 
> I see the `/usr/local/cuda/include/crt/host_config.h` header file. I think if gcc is also installed using spack, header files in system directory would not be used. The idea of `spack` is to make building packages machine/system independent, i.e., all dependent packages would be installed in a spack specific location, instead of using existing libraries in the system.

I used gcc installed by spack.
That's the output for gcc --version:
gcc (Spack GCC) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
And I used the command according to the instruction.

**Comment by World-Worst-Detector** [comment]
> > > > Thank you. But I got those errors:
> > > > /usr/local/cuda/include/crt/host_config.h:119:2: error: #error -- u
> > > > nsupported GNU version! gcc versions later than 7 are not supported
> > > > !
> > > > CMake Error at omptarget-nvptx_generated_omptarget-nvptx.cu.o.RelWi
> > > > thDebInfo.cmake:215 (message):
> > > > make[2]: *** [libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nv
> > > > ptx.dir/src/omptarget-nvptx_generated_omptarget-nvptx.cu.o] Error 1
> > > 
> > > 
> > > Thanks! This is an interesting problem.
> > > May I get the commands you run that trigger this error message?
> > 
> > 
> > I just use the command:
> > spack install llvm-openmp@romp-mod%gcc@9.2.0
> 
> I see the `/usr/local/cuda/include/crt/host_config.h` header file. I think if gcc is also installed using spack, header files in system directory would not be used. The idea of `spack` is to make building packages machine/system independent, i.e., all dependent packages would be installed in a spack specific location, instead of using existing libraries in the system.

I followed the instructions, I uploaded the spack build output in my forked repo, this is the link:
https://github.com/World-Worst-Detector/romp

**Comment by zygyz** [comment]
> > > > > Thank you. But I got those errors:
> > > > > /usr/local/cuda/include/crt/host_config.h:119:2: error: #error -- u
> > > > > nsupported GNU version! gcc versions later than 7 are not supported
> > > > > !
> > > > > CMake Error at omptarget-nvptx_generated_omptarget-nvptx.cu.o.RelWi
> > > > > thDebInfo.cmake:215 (message):
> > > > > make[2]: *** [libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nv
> > > > > ptx.dir/src/omptarget-nvptx_generated_omptarget-nvptx.cu.o] Error 1
> > > > 
> > > > 
> > > > Thanks! This is an interesting problem.
> > > > May I get the commands you run that trigger this error message?
> > > 
> > > 
> > > I just use the command:
> > > spack install llvm-openmp@romp-mod%gcc@9.2.0
> > 
> > 
> > I see the `/usr/local/cuda/include/crt/host_config.h` header file. I think if gcc is also installed using spack, header files in system directory would not be used. The idea of `spack` is to make building packages machine/system independent, i.e., all dependent packages would be installed in a spack specific location, instead of using existing libraries in the system.
> 
> I followed the instructions, I uploaded the spack build output in my forked repo, this is the link:
> https://github.com/World-Worst-Detector/romp

Thanks. After I looked at the build file. It is probably because your system has cuda support. And llvm-openmp's cmake flag `LIBOMPTARGET_NVPTX_ENABLE_BCLIB` is set to true by default:
https://github.com/llvm-mirror/openmp 

So if a system supports building the gpu offloading plugin, cmake would tell the compiler to build one, but since the compiler does not support cuda, it emits the error message. 

I would try to turn this flag off to disable building gpu offloading plugin. I changed the spack build file for llvm-openmp in the `romp-build` branch. Please pull the branch again and give it a try. 

If it still does not work, please try building using clang/llvm. `spack install llvm` would install the compiler.

**Comment by World-Worst-Detector** [comment]
> > > > > > Thank you. But I got those errors:
> > > > > > /usr/local/cuda/include/crt/host_config.h:119:2: error: #error -- u
> > > > > > nsupported GNU version! gcc versions later than 7 are not supported
> > > > > > !
> > > > > > CMake Error at omptarget-nvptx_generated_omptarget-nvptx.cu.o.RelWi
> > > > > > thDebInfo.cmake:215 (message):
> > > > > > make[2]: *** [libomptarget/deviceRTLs/nvptx/CMakeFiles/omptarget-nv
> > > > > > ptx.dir/src/omptarget-nvptx_generated_omptarget-nvptx.cu.o] Error 1
> > > > > 
> > > > > 
> > > > > Thanks! This is an interesting problem.
> > > > > May I get the commands you run that trigger this error message?
> > > > 
> > > > 
> > > > I just use the command:
> > > > spack install llvm-openmp@romp-mod%gcc@9.2.0
> > > 
> > > 
> > > I see the `/usr/local/cuda/include/crt/host_config.h` header file. I think if gcc is also installed using spack, header files in system directory would not be used. The idea of `spack` is to make building packages machine/system independent, i.e., all dependent packages would be installed in a spack specific location, instead of using existing libraries in the system.
> > 
> > 
> > I followed the instructions, I uploaded the spack build output in my forked repo, this is the link:
> > https://github.com/World-Worst-Detector/romp
> 
> Thanks. After I looked at the build file. It is probably because your system has cuda support. And llvm-openmp's cmake flag `LIBOMPTARGET_NVPTX_ENABLE_BCLIB` is set to true by default:
> https://github.com/llvm-mirror/openmp
> 
> So if a system supports building the gpu offloading plugin, cmake would tell the compiler to build one, but since the compiler does not support cuda, it emits the error message.
> 
> I would try to turn this flag off to disable building gpu offloading plugin. I changed the spack build file for llvm-openmp in the `romp-build` branch. Please pull the branch again and give it a try.
> 
> If it still does not work, please try building using clang/llvm. `spack install llvm` would install the compiler.

Hi, I can install OpenMP with spack install llvm. When I tried to run ./myApp.inst, the application has no response.
$./myApp.inst 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0220 13:30:36.815795  5933 RompLib.cpp:125] ompt_start_tool on executable: /home/dataracebench/micro-benchmarks/myApp.inst
When I tired $ldd myApp.inst, it has a new libgomp.so.1 which is not appeared in past instrumented application. Is that could be the reason crush the library?
