### ISSUE TITLE
Trouble using romp with an example program

### ISSUE THREAD

**Issue by nbushehri** [zygyz/romp#4]
I can now build romp by checking out commit 9dd4e9e and following the installation guide with spack. However, I'm having problems using romp with and example program. I run the following command:

`gcc -g -fopenmp -lomp DRB001.c -o test`

But I get the following error:

`/usr/bin/ld: cannot find -lomp`

Moreover, I'm adding the symlink to libomp.so.
Could it be that more environment variables need to be set up than mentioned in the readme?

Thanks

**Comment by zygyz** [comment]
> I can now build romp by checking out commit [9dd4e9e](https://github.com/zygyz/romp/commit/9dd4e9e9b8fc3158723626a023aa6b1f619734ec) and following the installation guide with spack. However, I'm having problems using romp with and example program. I run the following command:
> 
> `gcc -g -fopenmp -lomp DRB001.c -o test`
> 
> But I get the following error:
> 
> `/usr/bin/ld: cannot find -lomp`
> 
> Moreover, I'm adding the symlink to libomp.so.
> Could it be that more environment variables need to be set up than mentioned in the readme?
> 
> Thanks

May I see your environment variable setup? It could be some typo in the spack command. 
Thanks!

**Comment by zygyz** [comment]
> I can now build romp by checking out commit [9dd4e9e](https://github.com/zygyz/romp/commit/9dd4e9e9b8fc3158723626a023aa6b1f619734ec) and following the installation guide with spack. However, I'm having problems using romp with and example program. I run the following command:
> 
> `gcc -g -fopenmp -lomp DRB001.c -o test`
> 
> But I get the following error:
> 
> `/usr/bin/ld: cannot find -lomp`
> 
> Moreover, I'm adding the symlink to libomp.so.
> Could it be that more environment variables need to be set up than mentioned in the readme?
> 
> Thanks

~~It is probably because the LD_LIBRARY_PATH for llvm_openmp is not set properly.~~

Since it is compile time error, one should set the LIBRARY_PATH for llvm-openmp directory. I have updated the readme to fix the issue.

**Comment by nbushehri** [comment]
Thanks. Using the updated README, I can now compile a test program. However, when I run test.inst which is similar to DRB001 from data race bench, I don't see anything being reported (I also set ROMP_REPORT_LINE and ROMP_REPORT).

When running ldd on test, i get the following output:

	linux-vdso.so.1 =>  (0x00007ffe57579000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc6da85000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdc6de4f000)

Compared to test, running ldd on test.inst includes a lot more shared libraries and they all appear to be pointing to the spack installations. However, unlike the README, ldd test.inst has a dependency on libgomp.so. instead of libomp.so, which may be causing the issue.

**Comment by zygyz** [comment]
> Thanks. Using the updated README, I can now compile a test program. However, when I run test.inst which is similar to DRB001 from data race bench, I don't see anything being reported (I also set ROMP_REPORT_LINE and ROMP_REPORT).
> 
> When running ldd on test, i get the following output:
> 
> ```
> linux-vdso.so.1 =>  (0x00007ffe57579000)
> libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc6da85000)
> /lib64/ld-linux-x86-64.so.2 (0x00007fdc6de4f000)
> ```
> 
> Compared to test, running ldd on test.inst includes a lot more shared libraries and they all appear to be pointing to the spack installations. However, unlike the README, ldd test.inst has a dependency on libgomp.so. instead of libomp.so, which may be causing the issue.

Yes. The instrumented binary needs to use the libomp.so, which contains OMPT callback functions implementation. Also, when compiling with gcc or clang, the -fopenmp option needs to be specified although -lomp asks gcc/clang to link the libomp.so library.
